spring.application.name=SpringAIAdvance
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

spring.ai.openai.api-key={YOUR API KEY}
spring.ai.openai.model=gpt-5.1
spring.ai.openai.temperature=0.3
spring.ai.openai.max-tokens=100
spring.ai.openai.top-p=0.5
spring.ai.openai.frequency-penalty=0.4
spring.ai.openai.presence-penalty=0.4